// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_UXtkH2_rkoMzPJsQ7rwSSVlziVCO8Ck',
    appId: '1:971076821395:android:890145ce8f4ca4ae388866',
    messagingSenderId: '971076821395',
    projectId: 'handout-flutter-app',
    storageBucket: 'handout-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV4sv7wSsezgtvLPaROAtlxQ1J8Jufv5k',
    appId: '1:971076821395:ios:bfc98cb4208ab47d388866',
    messagingSenderId: '971076821395',
    projectId: 'handout-flutter-app',
    storageBucket: 'handout-flutter-app.appspot.com',
    androidClientId: '971076821395-geu8tmgsnoockad92b2n0i0hug9kavrc.apps.googleusercontent.com',
    iosClientId: '971076821395-r8e4qjtj3vn1m7r6dvkrluflt6rfia6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.edenTask',
  );
}
